apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "kibana.fullname" . }}
  namespace: default
  labels:
    app: {{ template "kibana.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "kibana.name" . }}
  template:
    metadata:
      name: {{ template "kibana.name" . }}
      labels:
        app: {{ template "kibana.name" . }}
      annotations:
        networks: '[
        { "name": "{{  .Values.networks.overlaynet }}" }
      ]'
    spec:
      containers:
      - name: kibana
        imagePullPolicy: Always
        image: {{ .Values.image.repository }}/kibana
        ports:
        - containerPort: 5601
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      nodeSelector:
        nodetype: master
