# EDCOP Stenographer Chart values
images:
  stenographer: miked235/stenographer
networks:
  # Overlay is the name of the default cni network
  overlay: calico
  # Passive is the name of the sriov interface
  passive: passive
volumes:
  logs:
    packets: /var/EDCOP/data/logs/stenographer/packets
    index: /var/EDCOP/data/logs/stenographer/index
nodeSelector:
  nodetype: worker
stenographerConfig:
  maxFileSize: 4194304
  maxOpenFiles: 1000000
  # Requests are set to accommodate limited resource VMs
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 2
    memory: 4G

